=== Senior Lecturer (Games Computing)

// icon:calendar[title="Period"]
*_January 2014 to May 2017_*
-
// icon:group[title="Employee"]
{link-lincolnUni}[University of Lincoln , role="external", window="_blank"]

* *Degree Programmer Leader (Games Computing)*
* *Co-op leader of {link-lincolnUniIntLab}[Interactive Technologies Research Group (intLab)]*

* Led team delivering Lincoln's {link-lincolnUniGamesComputing}[Games Computing] taught programme (BSc and MComp)
* Engaged in internationally published research focused around “Creative play in public spaces”, using Games Technologies
* Supervised post-graduate research students (PhD and MSc). Pastoral support of students across programmes
* Developed and delivered taught content for UG and PG programmes (Graphics, Games Programming, Game Engine Architectures, Advanced Graphics)
* Wrote new software for both teaching and research in C++, Java, C#, using low-level libraries (OpenGL, GLSL, SDL2) and high-level Game Engines (Unity, Unreal Engine), affording very highly rated programmes
* Evangelized good practice and disciplines of using software development support tools in teaching and research practices (versioning, issue tracking, communication support tools, automated testing)
* Advocated for equality, diversity and inclusion at all teaching and learning levels, and across the department (Athena Swan committee)
