=== Technical Director

// icon:calendar[title="Period"]
*_December 2019 to August 2020_*
-
// icon:group[title="Employee"]
{link-mastersOfPie}[Masters Of Pie Ltd. , role="external", window="_blank"] +

Supported the migration from .NET Framework 4 versions to .NET Standard and .NET core, along with finding/replacing tooling and libraries to allow the migration.

* Introduced the team to healthy code-review and testing practices, writing documentation for future selves, as well as discussing, agreeing and revisiting internal ways-of-working. 

* Engaged at all levels of work, from pair programming and building out CI/CD systems, through to high-level strategic discussions, stakeholder consultations, roadmapping and decision making. Interacted daily with whole team and reported directly to the founders

* Drove the project planning and development for a rewrite of the core engine, with detailed short-term and long-term roadmaps. Acted as a technical solution architect with external partners on future pathways.
