== Events & Performances

=== EyeResonator

* Collaboration with Brigitta Zics, Gavin Wood, Adam Parkinson

* Eye Resonator At The Power Plant, Kelenföld Power Plant Station, Budapest. Curated by Peternák Miklós. icon:calendar[title="Period"] _April 30 - May 3, 2015_
* Kinetica Art Fair, Old Truman Brewery. icon:calendar[title="Period"] _October 16-19, 2014_
* Fictional interludes I, Culture Lab, Newcastle University. Curated by Gabi Arrigoni. icon:calendar[title="Period"] _June 3-5, 2014_

=== Music Rader

* Bestival 2012 – Tomorrow's World Arena .Isle of Wight, UK. icon:calendar[title="Period"] _September 5-8, 2012_

=== NightinGallery

* Collaboration with Robyn Taylor and Guy Schofield
  ** BBC Free Thinking Festival 2011, Sage Gateshead, UK. icon:calendar[title="Period"] _November 4-6, 2011_
  ** Bestival 2011- Tomorrow's World Arena .Isle of Wight, UK. icon:calendar[title="Period"] _September 8-11, 2011_
  ** Jam 46, Culture Lab – Newcastle, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _August 18. 2011_

=== HumanAquarium

* Collaboration with Robyn Taylor and Guy Schofield
  ** Laval Virtual 2011, Laval, France. icon:calendar[title="Period"] _April 6-10, 2011_
  ** Jam 45, Culture Lab – Newcastle, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _December 2. 2010_
  ** Interactive Tabletops and Surfaces 2010, Saarbrücken, Germany. icon:calendar[title="Period"] _November 7-10, 2010_
  ** BBC Free Thinking Festival 2010, Sage Gateshead, UK. icon:calendar[title="Period"] _November 5-7, 2010_
  ** interspace2010, Banff Centre, Banff, Canada. icon:calendar[title="Period"] _June 25, 2010_
  ** Webdesign International Festival, Limoges, France. icon:calendar[title="Period"] _June 3-5, 2010_
  ** Maker Faire UK, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _March 13-14, 2010_
  ** Centre for Life, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _November 14-15, 2009_
  ** Culture Lab Relaunch, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _October 22, 2009_
  ** Dove Marine Laboratory, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _October 14, 2009_
  ** Public Announcement, Dance City, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _October 2, 2009_

=== MyGreatNorthRun

* Collaboration with Tom Bartindale, Rachel Clarke
  ** Interactive Tabletops and Surfaces 2010, Saarbrücken, Germany. icon:calendar[title="Period"] _November 7-10, 2010_
  ** *3 month installation* - Great North Museum: Hancock, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _July 17 - October 17, 2010_

=== Binary-furniture

* Collaboration with Tom Schofield, Bettina Nissen and Codha Design Ltd.
  ** Baltic Centre for Contemporary Art, Gateshead, UK. icon:calendar[title="Period"] _October 22-24, 2010_

=== Sundroids

* Collaboration with Jamie Allen, Rachel Clarke, Kamilla Wajda, Karim Ladha
  ** Harehope quarry, Bishop Auckland, UK. icon:calendar[title="Period"] _October 21-21, 2010_

=== RM840

* Collaboration with Kole Chen, Adriana Rojas Viquez
  ** Render 10, Curtis Mayfield House, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _September 23-27, 2010_

=== Borrowers @ Nuffin like a puffin

* Collaborations with Areti Galani
  ** Seven Stories, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _July 2010 – June 2011_

=== The Virtual Human

* Newcastle Science Festival, Informatics Research Institute, Newcastle upon Tyne, UK. icon:calendar[title="Period"] _March 12 & 19, 2006_
