== Technical Skills

Languages and Specifications:: C, {cpp}, Python, Javascript,  Java, C#/.NET, R, PHP

Markup languages etc:: (X)HTML, CSS, XML, Json, Asciidoc, Markdown

Operating Systems:: icon:linux[] Linux (Ubuntu Server, Ubuntu, Xubuntu, Fedora, Raspbian), icon:windows[] Windows

Databases:: MySQL, Postgres, MongoDB, SQLite

3D:: OpenGL, OpenGL ES, WebGL, Extensive 3D knowledge and background, model loading and manipulation, VR (head-mounted, cave-based), Ogre3D

Games:: Games Programming, Graphics, Game Engine Architectures, Games Design, Games Research

Physical Computing:: Arduino/Teensduino, RaspberryPi, AVR, PIC, DMX / MIDI / OSC, Audio, Servo/Stepper Motors, Electronics, Accelerometers

Making/Fabrication:: 3D printing (FDM, SLS, SLA, Laser Cuttin, Milling (woods, plaster, paint), Hand and power tools, Lathes (non-CNC)

Custom / multimodal Interfaces:: Kinect (1 & 2), (multi)touch, anoto pens, geolocation

Infrastructure / System Administration:: Bare metal deployment (theforeman, manual, PXE), Configuration Management (salt, puppet, manual), LDAP, DHCP, DNS, Security considerations

Web / Cloud:: nodejs, python, apache, AWS/EC2, meteor, github, bitbucket, gitlab

Mobile:: Java, Cross-platform (Cordova/phonegap), geolocation, database connected

Software Engineering:: Versioning, DevOps, OOP, Design Patterns, Unit testing, Continuous Integration

Tools:: Visual Studio, Eclipse, Atom, Maven, Gradle, Git, Subversion, Asciidoc(tor), Travis

Data-intensive processing / Statistics:: R, iPython, SPSS, MatLab, Python Pandas, NumPy, MatPlotLib, Computer Vision (OpenCV), OpenCL / SyCL / CUDA
