== Technical Skills

Languages and Specifications:: C, {cpp}(11,14,17), Python, Javascript, Java, C#/.NET, PHP

Build Systems and dependency managers:: CMake, Premake, Conan.io, vcpkg, npm, yarn, Maven, Gradle

3D and Games Engines:: Extensive 3D Graphics, games and geometry processing capabilities - OpenGL, OpenGL ES, Vulkan, WebGL, three.js, VR (head-mounted and cave-based), Unreal Engine 4, Ogre3D, Godot Engine, Unity3D

Markup languages etc:: (X)HTML, CSS, XML, JSON, Asciidoc(tor), reStructuredText, Markdown

Platforms:: Linux icon:linux[] (Ubuntu Server, Ubuntu, Xubuntu, Fedora, Raspbian), Windows icon:windows[], OS X icon:apple[], Android icon:android[]

Databases:: MySQL, Postgres, MongoDB, Cassandra, ElasticSearch, SQLite

Physical Computing:: Arduino/Teensduino, RaspberryPi, AVR, PIC, DMX / MIDI / OSC, Audio, Servo/Stepper Motors, Electronics, Accelerometers

Web / Ops / Infrastructure / System Administration:: Nodejs, Apache, Electron, Flask,  AWS/EC2, Docker, openTracing, Swagger/openAPI, REST, Bare metal deployment (theforeman, PXE), Config Management (salt, puppet, chef), LDAP, DHCP, DNS

Software Engineering:: Git/SVN, CI/CD (Travis, Jenkins, GitLabCI, appveyor), Github, Atlassian/Bitbucket, Jira, Gitlab

Data-intensive processing / Statistics:: Jupyter, iPython, R, SPSS, MatLab, Python Pandas, NumPy, MatPlotLib, Computer Vision (OpenCV), OpenCL / SyCL / CUDA / HPX

////

Making/Fabrication:: 3D printing (FDM, SLS, SLA, Laser Cutting), Milling (woods, plaster, paint), Hand and power tools, Lathes (non-CNC)

Custom / multimodal Interfaces:: Kinect (1 & 2), (multi)touch, anoto pens, audio-focused (hands-free, eyes-free), geolocation,


Tools:: Visual Studio, Eclipse, CLionAtom, , Asciidoc(tor), Travis

////
