== Technical Skills

//TODO languages?? Swagger/openAPI, REST, versions??
Languages and Specifications:: C, {cpp}, Python, Javascript,  Java, C#/.NET, R, PHP

//TODO build systems ++??
Build Systems and dependency managers:: CMake, Premake, Conan.io, vcpkg,

//TODO other tooling - openTelemetry/tracing/census, elasticSearch, JSON

// TODO systems design etc
//  Knowledge of modern system designs: internet services architectures & designs of distributed systems
// Knowledge with Big Data technologies like Hadoop/HDFS/HBase, Kafka/Akka, etc
// Knowledge of Database technologies: relational and NoSQL 

Markup languages etc:: (X)HTML, CSS, XML, Json, Asciidoc, reStructuredText, Markdown

Operating Systems:: Linux (Ubuntu Server, Ubuntu, Xubuntu, Fedora, Raspbian) icon:linux[], Windows icon:windows[], OS X icon:apple[]

Databases:: MySQL, Postgres, MongoDB, SQLite

//TODO Add vulkan?
3D:: OpenGL, OpenGL ES, WebGL, Extensive 3D knowledge and background, model loading and manipulation, VR (head-mounted, cave-based), Ogre3D, three.js

//TODO add Game Engines? Godot, UE4, Unity?

//TODO multi-core, parallel, hpc, sycl

Games:: Games Programming, 3D and 2D Graphics, Game Engine Architectures, Games Design, Games Research

Physical Computing:: Arduino/Teensduino, RaspberryPi, AVR, PIC, DMX / MIDI / OSC, Audio, Servo/Stepper Motors, Electronics, Accelerometers

Making/Fabrication:: 3D printing (FDM, SLS, SLA, Laser Cutting), Milling (woods, plaster, paint), Hand and power tools, Lathes (non-CNC)

Custom / multimodal Interfaces:: Kinect (1 & 2), (multi)touch, anoto pens, audio-focused (hands-free, eyes-free), geolocation,

//TODO devops
Infrastructure / System Administration:: Bare metal deployment (theforeman, manual, PXE), Configuration Management (salt, puppet, manual), LDAP, DHCP, DNS, Security considerations

//TODO add technical web skills
Web:: Nodejs, Python, Apache, AWS/EC2, Electron,

//TODO cloud + docker + kubernetes
Cloud:: AWS/EC2, Digital Ocean, Azure

Mobile:: Java, Cross-platform (Cordova/phonegap), geolocation, database connected

Software Engineering:: Versioning (git, svn), DevOps, OOP, Design Patterns, Unit testing, Continuous Integration

// TODO ??? atlassian? jira?  Collaboration tools?
Project Management:: Github, Bitbucket, Gitlab

Tools:: Visual Studio, Eclipse, Atom, Maven, Gradle, Asciidoc(tor), Travis

//TODO update stats, big data
Data-intensive processing / Statistics:: Jupyter, iPython, R, SPSS, MatLab, Python Pandas, NumPy, MatPlotLib, Computer Vision (OpenCV), OpenCL / SyCL / CUDA
