:author: John Shearer
:date: September 2016
:doctitle: {author} PhD BEng
ifdef::backend-pdf[:notitle:]
ifdef::backend-pdf[]
[discrete]
= {doctitle}
endif::[]

:email: shearer12345gmail.com

:phone: +44 (0)7703 112 946
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:experimental:
:source-language: asciidoc
:includedir: _includes
:sectnums!:
:toc: macro
:imagesdir: ../images
:pdf-page-size: A4

include::{includedir}/links.adoc[]

[discrete]
== *A fullstack human being*

'''

include::{includedir}/personalDetails.adoc[]

****
I am an interdisciplinary, collaborative, maker-builder-developer-researcher. My work walks between Computer Science and the Arts, so I work with people from all backgrounds to make, explore and understand meaningful experiences. To do this I use a myriad of technologies to support this process, whilst keeping the end user front and centre.

I lead projects at all levels - from high-level strategic discussions and planning with involved parties, to getting my hands dirty and building art installations and physical computing devices in the real world - whatever the project needs. My works have resulted in both academic papers and a large number of public performances and installations, both in the UK and internationally.

My underpinning ethos is to collaborate with people in a research driven approach to build valuable products. In the brief portfolio that follows I will demonstrate that I use my range of strong problem solving skills, excellent leadership and project management experience to deliver effective, novel projects and events.
****

toc::[]

<<<
include::{includedir}/professionalExperience.adoc[]

<<<

include::{includedir}/skillsTechnical.adoc[]

include::{includedir}/skillsResearch.adoc[]

<<<

include::{includedir}/projectsEventsAndPerformances.adoc[]

<<<

include::{includedir}/publications.adoc[]

include::{includedir}/education.adoc[]
